---
title: "GAS Model"
subtitle: "Generalized Autoregressive Score Model"
author: "Felipe Marques"
format: 
  revealjs:
    incremental: true
    theme: sky
editor: visual
---

## Sumário

1)  Introdução
2)  O modelo
3)  Comparações
4)  Casos Particulares
5)  Estimação

# Introdução

## Introdução

-   O modelo GAS é o caso geral de modelos de ST guiadas pelo *score* $s_t$. O *score* é usado na equação de atualização dos parâmetros e fornece uma direção natural para onde os parâmetros devem ser atualizados.

-   Utilizar essa abordagem ao invés de outras utilizadas em outros modelos faz com que os modelos baseados em *score* sejam naturalmente mais robustos a *outliers*.

# Modelo

## O modelo

O modelo GAS(p, q) pode ser descrito a partir de 3 equações:

1)  Especifica a distribuição dos retornos
2)  Apresenta a equação de atualização
3)  Especifica o vetor *score* ($s_t$)

------------------------------------------------------------------------

Assim, o modelo GAS(p, q) é dado da forma:

1)  $y_t \sim p(y_t|f_t, \cal{F_t};\theta)$
2)  $f_{t+1} = \omega + \sum_{i=1}^p A_is_{t-i+1} + \sum_{j=1}^q B_jf_{t-j+1}$
3)  $s_t = S_t\cdot \nabla_t$,

. . .

Onde,

$$
\nabla_t = \frac{\partial \textrm{ln}p(y_t|f_t,\cal{F_t};\theta)}{\partial f_t}
$$

------------------------------------------------------------------------

Lembrando de Calculo II que:

-   $\nabla \rightarrow$ vetor gradiente: vetor com as derivadas parciais de cada variável (ou parâmetro, no caso) de uma função.

-   Indica a direção de máximo crescimento de uma função.

# Comparações

## Score x Momento

-   def: modelos baseados nos momentos são aqueles onde a variável que guia a função atualização possui esperança igual o parâmetro de interesse (Ex: Garch)

. . .

::: columns
::: column
Garch(1,1) $$
y_t = \sigma_t\epsilon_t \\
\sigma_{t+1}^2 = \omega + \alpha y_t^2 + \beta\sigma_t^2
$$
:::

::: column
score $$
y_t = \sigma_t\epsilon_t \\
\sigma_{t+1}^2 = \omega + \alpha s_t + \beta\sigma^2_t \\
s_t \propto d\textrm{ln}p(y_t|\cdot)/d\sigma^2_t
$$
:::
:::

. . .

$\epsilon_t \sim N(0,1)$, $E(y_t) = 0$.

## Score x Momento

Mas, porque $y_t^2$? 🤔

. . .

$$
E(y_t^2) = E[E(y_t^2|\mathcal{F}_{t-1})] = E[E(\sigma_t^2\epsilon_t^2|\mathcal{F}_{t-1})] = E(\sigma_t^2) = \sigma_t^2
$$

. . .

::: columns
::: column
Moment based:

-   Os momentos guiam a atualização dos parâmetros

-   Mais sussetível a outliers
:::

::: column
Score based:

-   O *score* dá uma direção natural para atualização

-   A atualização é guiada pela característica da função. Torna o modelo mais robusto.
:::
:::

. . .

# Casos Particulares

## GARCH

Consideramos um modelo GAS(1, 1), com as seguintes espeficicações:

-   $y_t = \sigma_t\epsilon_t,~~\epsilon \sim N(0,1)$
-   $f_t = \sigma_t^2$
-   $S_t = \cal{I}_{t|t-1}^{-1}$

. . .

Podemos mostrar que esse modelo se reduz para um Garch(1,1)

$$
f_{t+1} = \omega + \alpha y_t^2 + \beta f_t, ~~ f_t = \sigma^2_t
$$

## MEM, ACD and ACI models

Consideramos um modelo GAS(1, 1), com as seguintes espeficicações:

-   $y_t = \mu_t\epsilon_t,~~\epsilon \sim Gamma(\alpha,\alpha)$
-   $f_t = \mu_t$
-   $S_t = \cal{I}_{t|t-1}^{-1}$, ${\cal{I}}_{t|t-1} = E_{t-1}(\nabla_t\nabla_t')$

. . .

Podemos mostrar que esse modelo se reduz para

$$
f_{t+1} = \omega + A_1(y_t - f_t) + B_1 f_t 
$$

------------------------------------------------------------------------

Os modelos ACD e ACI são casos especiais do modelo MEM.

-   Caso usemos $\alpha = 1$ em $p(y_t|\cdot)$, com a mesma equação de atualização, obtemos o modelo ACD.
-   Caso especifiquemos a distribuição exponencial em termos da intensidade ao invés da duração esperada, obtemos o modelo ACI(1, 1)

## Dynamic exponential family models

Nesse modelo, $y_t$ pode ser representado pela densidade

. . .

$$ p(y_t|f_t, \cal{F_t};\theta) = exp\{\gamma'y_t - c(\gamma) + h(y_t)\}$$

. . .

Onde $c(\cdot)$ e $h(\cdot)$ são funções escalares e $\gamma$ um vetor de parâmetros. Fazemos,

. . .

$$\gamma_t = d + Z f_t $$ com $d$ um vetor de constantes e $Z$ uma matriz de cargas. Fazendo, $S_t = \cal{I}^{-1}_{t|t-1}$:

------------------------------------------------------------------------

Encontramos,

. . .

$$s_t = [Z'\ddot{c}(\gamma_t)]^{-1}Z'[\gamma_t - \dot{c}(\gamma_t)] $$

. . .

onde,

-   $\dot{c}(\gamma_t) = \partial c(\gamma_t)/\partial\gamma_t$
-   $\ddot{c}(\gamma_t) = \partial^2 c(\gamma_t)/\partial\gamma_t\partial\gamma_t'$

# Estimação

------------------------------------------------------------------------

A estimação dos parâmetros desconhecidos é feitas por máxima verossimilhança.

Para fazer isso, precisamos:

-   Implementar a equação de atualização
-   Avaliar $\ell_t$ em um valor $\theta^*$ de $\theta$.

. . .

onde $\ell_t$ é a função de log-verossimilhança.
